- build.gradle.kts
- gradle.properties
- scripts/export-keycloak-config.sh
- src/main/kotlin/fi/metatavu/lipsanen/keycloak/KeycloakAccessToken.kt
- src/main/kotlin/fi/metatavu/lipsanen/keycloak/KeycloakAdminClient.kt
- src/main/kotlin/fi/metatavu/lipsanen/keycloak/KeycloakClient.kt
- src/main/kotlin/fi/metatavu/lipsanen/persistence/AbstractRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/lipsanen/rest/UserRole.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/main/resources/kc-admin.json
- src/native-test/kotlin/fi/metatavu/lipsanen/functional/NativeSystemTestIT.kt
- src/native-test/kotlin/fi/metatavu/lipsanen/functional/NativeUserTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/ProjectTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/SystemTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TestBuilder.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/UserTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/UserTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/resources/KeycloakResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/settings/DefaultTestProfile.kt
- src/test/resources/application.properties
- src/test/resources/kc.json
https://github.com/Metatavu/lipsanen-project-management-api/issues/6
Introduces env variables:
For admin user:
```
lipsanen.keycloak.admin.realm
lipsanen.keycloak.admin.secret
lipsanen.keycloak.admin.client
lipsanen.keycloak.admin.user
lipsanen.keycloak.admin.password
```
> Feature 6 user endpoints

- src/main/kotlin/fi/metatavu/lipsanen/keycloak/KeycloakAdminClient.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/lipsanen/tocoman/TocomanController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/main/resources/db/changeLog.xml
- src/main/resources/kc-admin.json
- src/test/kotlin/fi/metatavu/lipsanen/functional/ProjectTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TestBuilder.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/UserTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/ProjectTestBuilderResource.kt
- src/test/resources/kc.json
https://github.com/Metatavu/lipsanen-project-management-api/issues/8
> Feature 8 access rights

- .gitmodules
- build.gradle.kts
- src/main/kotlin/fi/metatavu/lipsanen/companies/CompaniesApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/companies/CompanyController.kt
- src/main/kotlin/fi/metatavu/lipsanen/companies/CompanyEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/companies/CompanyRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/companies/CompanyTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/main/resources/db/changeLog.xml
- src/native-test/kotlin/fi/metatavu/lipsanen/functional/NativeCompanyTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/CompaniesTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/CompanyTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/ProjectTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/UserTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/CompanyTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/ProjectTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/UserTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/resources/KeycloakResource.kt
- src/test/resources/kc.json
https://github.com/Metatavu/lipsanen-project-management-api/issues/10
> Feature 10 companies support

- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/themes/ProjectThemeController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/themes/ProjectThemeEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/themes/ProjectThemeRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/themes/ProjectThemeTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/themes/ProjectThemesApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserTranslator.kt
- src/main/resources/db/changeLog.xml
- src/native-test/kotlin/fi/metatavu/lipsanen/functional/NativeProjectThemeTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/ProjectThemeTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/ProjectTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/ProjectThemeTestBuilderResource.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/12
> Feature 12 project themes

- build.gradle.kts
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectTranslator.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/lipsanen/functional/ProjectTestIT.kt
> Feature 14 project status support

- src/main/kotlin/fi/metatavu/lipsanen/persistence/AbstractRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/MilestoneController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/MilestonesApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskEntityRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TasksApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/connections/TaskConnectionController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/connections/TaskConnectionEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/connections/TaskConnectionRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/connections/TaskConnectionTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/connections/TaskConnectionsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/rest/AbstractApi.kt
- src/main/resources/db/changeLog.xml
- src/native-test/kotlin/fi/metatavu/lipsanen/functional/NativeTaskConnectionTestIT.kt
- src/native-test/kotlin/fi/metatavu/lipsanen/functional/NativeTaskTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/MilestoneTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskConnectionTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/MilestoneTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/TaskConnectionTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/TaskTestBuilderResource.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/19
> Feature 19 tasks

- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/UserTestIT.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/24
> filter out admin user

- src/main/kotlin/fi/metatavu/lipsanen/keycloak/KeycloakAdminClient.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/UserTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/UserTestBuilderResource.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/26
> added roles to user

- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/MilestoneController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/MilestoneEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/MilestoneRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/MilestoneTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/MilestonesApiImpl.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/lipsanen/functional/MilestoneTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/MilestoneTestBuilderResource.kt
> Feature 33 milestone original start end dates

- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskAssigneeEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskAssigneeRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskAttachmentEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskAttachmentRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskEntityRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TasksApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskTestIT.kt
> Feature task schema missing parameters for task card

- build.gradle.kts
- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationsController.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/notificationevents/NotificationEventEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/notificationevents/NotificationEventRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/notificationevents/NotificationEventTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/notificationevents/NotificationEventsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/notificationevents/NotificationEventsController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TasksApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/proposals/ChangeProposalController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/main/resources/db/changeLog.xml
- src/native-test/kotlin/fi/metatavu/lipsanen/functional/NativeNotificationEventsTestIT.kt
- src/native-test/kotlin/fi/metatavu/lipsanen/functional/NativeNotificationsCleanupTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/NotificationEventsTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/NotificationsCleanupTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/NotificationEventsTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/NotificationTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/settings/NotificationsTestProfile.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/38
2 new env variables:
cron.notifications.cleanup = quartz cron expression
notifications.cleanup.delay.days = value should be int
> Feature 38 project notifications

- src/main/kotlin/fi/metatavu/lipsanen/rest/MetadataTranslator.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskTestIT.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/52
> metadata translation

- src/main/kotlin/fi/metatavu/lipsanen/companies/CompaniesApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/rest/MetadataTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/UserTestBuilderResource.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/56
> keycloak id filtering, removed metadata translator user resolution

- src/main/kotlin/fi/metatavu/lipsanen/companies/CompaniesApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/notificationevents/NotificationEventsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/positions/JobPositionApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/MilestonesApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TasksApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/comments/TaskCommentsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/connections/TaskConnectionsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/proposals/ChangeProposalsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/themes/ProjectThemesApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskConnectionTestIT.kt
> Feature 61 fixed coroutine timeout issue

- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/connections/TaskConnectionController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/connections/TaskConnectionsApiImpl.kt
https://github.com/Metatavu/lipsanen-project-management-api/
> connection updates

- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/test/resources/kc.json
https://github.com/Metatavu/lipsanen-project-management-api/issues/68
> users attribute

- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TasksApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/comments/TaskCommentsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/proposals/ChangeProposalController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/proposals/ChangeProposalsApiImpl.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/ChangeProposalTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/MilestoneTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/NotificationEventsTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/NotificationsCleanupTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskCommentTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskConnectionTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/ChangeProposalTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/TaskCommentTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/TaskTestBuilderResource.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/66
> removed milestone level from path

- src/main/kotlin/fi/metatavu/lipsanen/companies/CompaniesApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/UserTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/UserTestBuilderResource.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/73
> Feature 73 users project filter

- build.gradle.kts
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskEntityRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/lipsanen/functional/ChangeProposalTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/UserTestBuilderResource.kt
> Added dependent user ID to task

- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/proposals/ChangeProposalsApiImpl.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/ChangeProposalTestIT.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/40
> disallow updating the accepted/rejected proposals

- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskController.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/NotificationEventsTestIT.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/78
> removed duplicated notifications for task assignments

- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/proposals/ChangeProposalController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/proposals/ChangeProposalRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/proposals/ChangeProposalsApiImpl.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/ChangeProposalTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/ChangeProposalTestBuilderResource.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/83
> listing change proposals without project id

- src/main/kotlin/fi/metatavu/lipsanen/projects/milestones/tasks/TaskController.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/MilestoneTestIT.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/85
> extending milestone to task

- src/main/kotlin/fi/metatavu/lipsanen/companies/CompaniesApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/UserTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/UserTestBuilderResource.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/90
INCLUDES PREVIOUS PRS
> Job positions filter

- src/main/kotlin/fi/metatavu/lipsanen/milestones/MilestoneController.kt
- src/main/kotlin/fi/metatavu/lipsanen/tasks/TaskController.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/MilestoneTestIT.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/96
> readonly and calculated estimated readiness for the milestone

- src/main/kotlin/fi/metatavu/lipsanen/milestones/MilestonesApiImpl.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/MilestoneTestIT.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/98
> milestone removal cannot happen with tasks present

- src/main/kotlin/fi/metatavu/lipsanen/companies/CompaniesApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationsController.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/notificationevents/NotificationEventsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/proposals/ChangeProposalsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/tasks/TaskController.kt
- src/main/kotlin/fi/metatavu/lipsanen/tasks/TasksApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/tasks/comments/TaskCommentController.kt
- src/main/kotlin/fi/metatavu/lipsanen/tasks/comments/TaskCommentUserRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/tasks/comments/TaskCommentsApiImpl.kt
- src/main/kotlin/fi/metatavu/lipsanen/tocoman/TocomanController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/lipsanen/functional/TaskTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/UserTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/UserTestBuilderResource.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/86
> user keycloak id replaced with id

- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectController.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/projects/ProjectTranslator.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/lipsanen/functional/ProjectTestIT.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/impl/ProjectTestBuilderResource.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/101
> added estimated start/end time to project

- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/107
> removed unneeded check

- src/main/kotlin/fi/metatavu/lipsanen/tasks/TaskController.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/105
> task status update fix

- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationEntity.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationRepository.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationTranslator.kt
- src/main/kotlin/fi/metatavu/lipsanen/notifications/NotificationsController.kt
- src/main/kotlin/fi/metatavu/lipsanen/proposals/ChangeProposalController.kt
- src/main/kotlin/fi/metatavu/lipsanen/tasks/TaskController.kt
- src/main/kotlin/fi/metatavu/lipsanen/tasks/comments/TaskCommentController.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/lipsanen/functional/NotificationEventsTestIT.kt
- removed messages
- added more data types with all needed data for localizing
- added change proposal reference
https://github.com/Metatavu/lipsanen-project-management-api/issues/109
Note:specs are not approved yet
> notification changes:

- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/resources/KeycloakResource.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/settings/DefaultTestProfile.kt
https://github.com/Metatavu/lipsanen-project-management-api/issues/120
> default role is always assigned to user

- src/main/kotlin/fi/metatavu/lipsanen/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/lipsanen/rest/UserRole.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UsersApiImpl.kt
- src/test/resources/kc.json
https://github.com/Metatavu/lipsanen-project-management-api/issues/122
> replaced user management admin functionality with admin

- src/main/kotlin/fi/metatavu/lipsanen/users/UserController.kt
- src/main/kotlin/fi/metatavu/lipsanen/users/UserTranslator.kt
- src/test/kotlin/fi/metatavu/lipsanen/functional/UserTestIT.kt
> Changed last login source from user events to user attribute
